server:
  port: 8088
spring:
  freemarker:
    charset: UTF-8
    cache: false
    check-template-location: true
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html